package scalaID3.models.frames

object FrameTypes extends Enumeration {
  type FrameType = Value

  val ContentGroup: FrameType        = Value("TIT1")
  val Title: FrameType               = Value("TIT2")
  val Subtitle: FrameType            = Value("TIT3")
  val Lead: FrameType                = Value("TPE1")
  val Band: FrameType                = Value("TPE2")
  val Conductor: FrameType           = Value("TPE3")
  val ModifiedBy: FrameType          = Value("TPE4")
  val Year: FrameType                = Value("TYER")
  val PartOfSet: FrameType           = Value("TPOS")
  val TrackNum: FrameType            = Value("TRCK")
  val Album: FrameType               = Value("TALB")
  val ContentType: FrameType         = Value("TCON")
  val Copyright: FrameType           = Value("TCOP")
  val Bpm: FrameType                 = Value("TBPM")
  val Composer: FrameType            = Value("TCOM")
  val Date: FrameType                = Value("TDAT")
  val Time: FrameType                = Value("TIME")
  val Delay: FrameType               = Value("TDLY")
  val EncodedBy: FrameType           = Value("TENC")
  val Writers: FrameType             = Value("TEXT")
  val AudioType: FrameType           = Value("TFLT")
  val InitialKey: FrameType          = Value("TKEY")
  val Languages: FrameType           = Value("TLAN")
  val Length: FrameType              = Value("TLEN")
  val MediaType: FrameType           = Value("TMED")
  val OriginalAlbum: FrameType       = Value("TOAL")
  val OriginalFilename: FrameType    = Value("TOFN")
  val OriginalWriters: FrameType     = Value("TOLY")
  val OriginalArtists: FrameType     = Value("TOPE")
  val OriginalReleaseDate: FrameType = Value("TORY")
  val FileOwner: FrameType           = Value("TOWN")
  val Publisher: FrameType           = Value("TPUB")
  val RecordingDates: FrameType      = Value("TRDA")
  val InternetRadio: FrameType       = Value("TRSN")
  val Picture: FrameType             = Value("APIC")
}
